# Generated by Django 5.0.3 on 2024-04-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_usercredentials_username_usercredentials_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={},
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='state',
            name='abbreviation',
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
