# Generated by Django 5.0.3 on 2024-04-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_state_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredentials',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
